name: 'Deploy Infrastructure'

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project'
        required: true
        default: 'doctolib-case-dataops'

env:
  PROJECT_NAME: ${{ github.event.inputs.project_name }}
  CREDENTIALS_GCP: ${{ secrets[github.event.inputs.project_name.replace('-', '_')] }}

jobs:
  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    # Step 1: Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Step 2: Set up Google Cloud credentials based on project name
    - name: Set up Google Cloud credentials
      id: setup_credentials
      run: |
          echo "$CREDENTIALS_GCP" > credentials.json

    # Step 3: Export GOOGLE_APPLICATION_CREDENTIALS environment variable
    - name: Export Google Application Credentials
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=credentials.json" >> $GITHUB_ENV

    # Step 4: Install Google Cloud SDK
    - name: Install Google Cloud SDK
      run: |
          echo "Installing Google Cloud SDK..."
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install -y google-cloud-sdk

    # Step 5: Create Google Cloud bucket if it doesn't exist
    - name: Create GCS Bucket if Not Exists
      run: |
          BUCKET_NAME="${{ env.PROJECT_NAME }}-terraform"
          if ! gsutil ls -b "gs://$BUCKET_NAME" &>/dev/null; then
            gsutil mb "gs://$BUCKET_NAME"
          fi

    # Step 6: Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Step 7: Initialize the Terraform configuration
    - name: Terraform Init
      run: terraform init 

    # Step 8: Check conformity of Terraform configuration files
    - name: Terraform Validate
      run: terraform validate 

    # Step 9: Run Terraform Plan to check for infrastructure changes
    - name: Terraform Plan
      id: plan
      run: terraform plan 

  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform_plan  # Ensure this job runs after the plan job
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    # Step 1: Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Step 2: Set up Google Cloud credentials based on project name
    - name: Set up Google Cloud credentials
      id: setup_credentials
      run: |
          echo "$CREDENTIALS_GCP" > credentials.json

    # Step 3: Export GOOGLE_APPLICATION_CREDENTIALS environment variable
    - name: Export Google Application Credentials
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=credentials.json" >> $GITHUB_ENV

    # Step 4: Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Step 6: Initialize the Terraform configuration
    - name: Terraform Init
      run: terraform init

    # Step 7: Run Terraform Apply to deploy the configuration
    - name: Terraform Apply
      run: terraform apply --auto-approve